# Generated by Django 5.1.4 on 2024-12-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pro1', models.CharField(max_length=100)),
                ('pd1', models.CharField(max_length=70)),
                ('pro2', models.CharField(max_length=100)),
                ('pd2', models.CharField(max_length=70)),
                ('pro3', models.CharField(max_length=100)),
                ('pd3', models.CharField(max_length=70)),
                ('ach1', models.CharField(max_length=100)),
                ('ad1', models.CharField(max_length=70)),
                ('ach2', models.CharField(max_length=100)),
                ('ad2', models.CharField(max_length=70)),
                ('ach3', models.CharField(max_length=100)),
                ('ad3', models.CharField(max_length=70)),
                ('adress', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
