# Generated by Django 5.1.4 on 2024-12-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_user_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
